### PR TITLE
Entity field based replacements for fileNames and Paths. And accept type as null or 'image'.

### PR DESCRIPTION
**Pull request by leonardobazico**
- Users can set entity field based replacements for fileNames and Paths
- Users can set the accept type as null or 'image'.

``` php
        $this->addBehavior('User.Uploadable', [
            'avatar_path' => [
                'field' => 'avatar_path',
                'path' => '{ROOT}{DS}{WEBROOT}{DS}uploads{DS}{model}{DS}avatar{DS}{primaryKey}{DS}',
                'fileName' => '{primaryKey}_avatar_' . $now . '.{extension}',
                'entityReplacements' => [
                    '{primaryKey}' => 'id',
                ],
                'accept_type' => 'image'
            ],
        ]);
```

### CODE REVIEW

**Comment by bobmulder** [comment]
Hi @leonardobazico!

First of all, thank you for your PR! Can you explain me what's solved by this PR? What does it do?
Also the code coverage decreased, so I would love to see some tests of it ;).

**Comment by leonardobazico** [comment]
Hi @bobmulder!

This PR add two features.

1 - Entity field based replacements for fileNames and Paths.
I need name to directories and files based on values of entity field. So the parameter entityReplacements in configuration of behavior will be use for this.

Ex.: 

``` php
        $this->addBehavior('User.Uploadable', [
            'avatar_path' => [
                'field' => 'avatar_path',
                'path' => '{ROOT}{DS}{WEBROOT}{DS}uploads{DS}{model}{DS}avatar{DS}{primaryKey}{DS}',
                'fileName' => '{primaryKey}_avatar_' . $now . '.{extension}',
                'entityReplacements' => [
                    '{primaryKey}' => 'id',
                ],
                'accept_type' => 'image'
            ],
        ]);
```

So when save a entity with primary key 3 where is '{primaryKey}' will be replace by 3.

2 - Set the accept type.
Today I need to accept only images in some cases. So if set the parameter accept_type as 'image', before get path and move file I check if the file is a image by mime type and the extension of file.

In future we can add more types accepts.

I'm working on tests.

**Comment by leonardobazico** [comment]
@bobmulder, I worked on tests only for UploadableBehavior that I changed code.

**Comment by bobmulder** [comment]
Hi @leonardobazico,

I've taken a look at your suggestions.

## Entity Replacements

I like the idea that you can use every variable of the entity, which would be great! However, I think we should make it easier. Take a look at the following code: https://github.com/cakemanager/cakephp-utils/blob/master/src/Model/Behavior/UploadableBehavior.php#L388-L394
I think we can expand that array simply by merging our entity in it.

## Accept Types

I see your issue: you want to validate on your uploaded file. Have you tried validating like the Cake way? Take a look at this: http://book.cakephp.org/3.0/en/core-libraries/validation.html#conditional-validation. I think that would work for you. And solving validation like the Cake way saves us a lot of work ;)

## Whats next

Assuming the problem of 'Accept types' is solved, I would suggest that you open up a new PR with the expansion of the `$replacements` array. A possible way is creating a protected method which requires the entity and generates the full array (including the existing replacements AND the entity).

Please be aware of other changes. When I get a PR I want to take a look at only the changed code. In this PR I saw a lot of spaces, naming, strange stuff, et cetera ;) I don't blame you, but be aware of it.

I really appreciate your contribution and I hope the tools help you with development. If you want to have a chat with me, you can reach me via https://gitter.im/bobmulder.

Good luck!

**Comment by leonardobazico** [comment]
@bobmulder, thanks for your suggestions. I'll try to make the changes this week.

**Pull request closed without merging**
